const BASE_URL = "http://localhost:8000/api";
const LOGIN_URL = "$BASE_URL/login";
const LOGOUT_URL = "$BASE_URL/logout";
const GET_TEAMS_URL = "$BASE_URL/user/teams?locale=en";
const GET_PLAYERS_URL = "$BASE_URL/teams/";
const GET_MATCHES_URL = "$BASE_URL/seasons/";
const ADD_PLAYERS_URL = "$BASE_URL/players";
const DELETE_PLAYERS_URL="$BASE_URL/players";
const GET_STAFFS_URL="$BASE_URL/teams/";
const GET_TRAININGS_URL="$BASE_URL/seasons/";
const GET_VIDEOS_URL="$BASE_URL/videos?team_id=";